name: App install and start

concurrency: 
  group: production
  cancel-in-progress: true

on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
    - uses: actions/checkout@v2
      with:
        clean: true

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x

    - name: Install dependencies
      run: npm install
        
    - name: Stop old server (ignore error)
      run: |
        killall -9 node || true

    - name: Remove old server in ~/soruce (ignore error)
      run: |
        rm -rf ~/source || true

    - name: Copy new server to ~/soruce
      run: |
        mkdir -p ~/source
        cp -R ./ ~/source

    - name: Build
      run: |
        cd ~/source
        npm run build
        
    - name: Run new server (in background)
      env:
        RUNNER_TRACKING_ID: ""
      run: |
        cd build
        nohup npm run start </dev/null >/dev/null 2>&1 &
